//! Ideals represented by a reduced Groebner basis.
//!
//! ```
//! use groebner::{Ideal, MonomialOrder, PolynomialRing, PrimeField};
//!
//! let ring = PolynomialRing::<PrimeField<32003>>::new(["x", "y"], MonomialOrder::GRevLex)?;
//! let ideal = Ideal::new(ring.parse_many("x^2 - y; y^2 - x")?)?;
//! assert!(ideal.contains(&ring.parse("x^4 - x")?)?);
//! assert_eq!(ideal.vector_space_dimension(), Some(4));
//! # Ok::<(), Box<dyn std::error::Error>>(())
//! ```

use crate::f4::{F4Field, groebner_basis_f4};
use crate::fglm;
use crate::field::Field;
use crate::groebner::{GroebnerError, finish_basis, prepare_input};
use crate::monomial::{Monomial, MonomialOrder};
use crate::polynomial::{Polynomial, Term};

#[derive(Debug, Clone, PartialEq)]
pub struct Ideal<F> {
    basis: Vec<Polynomial<F>>,
    nvars: usize,
    order: MonomialOrder,
}

impl<F: F4Field> Ideal<F> {
    /// The ideal generated by `generators`, with its reduced Groebner basis computed by F4.
    pub fn new(generators: Vec<Polynomial<F>>) -> Result<Self, GroebnerError> {
        Self::from_groebner_basis(groebner_basis_f4(generators, true)?)
    }

    /// The elimination ideal without the first `k` variables, still expressed in all variables.
    pub fn eliminate(&self, k: usize) -> Result<Self, GroebnerError> {
        let basis = if self.order.eliminates(k) {
            self.basis.clone()
        } else {
            let order = MonomialOrder::elimination(k, self.nvars - k);
            groebner_basis_f4(
                self.basis
                    .iter()
                    .map(|p| p.reorder(order.clone()))
                    .collect(),
                true,
            )?
        };
        let kept: Vec<_> = basis
            .into_iter()
            .filter(|p| {
                p.terms
                    .iter()
                    .all(|t| t.monomial.exponents()[..k].iter().all(|e| *e == 0))
            })
            .collect();
        if kept.is_empty() {
            return Ok(Self {
                basis: kept,
                nvars: self.nvars,
                order: self.order.clone(),
            });
        }
        Self::from_groebner_basis(kept)
    }

    /// Radical membership: `f` is in the radical iff `1 - t*f` and the ideal generate everything.
    pub fn radical_contains(&self, f: &Polynomial<F>) -> Result<bool, GroebnerError> {
        if self.basis.is_empty() {
            return Ok(f.is_zero());
        }
        let n = self.nvars + 1;
        let order = MonomialOrder::block(vec![
            (self.order.clone(), self.nvars),
            (MonomialOrder::Lex, 1),
        ]);
        let extend = |p: &Polynomial<F>, t_power: u32| {
            let terms = p
                .terms
                .iter()
                .map(|term| {
                    let mut e = term.monomial.exponents().to_vec();
                    e.push(t_power);
                    Term::new(term.coefficient.clone(), Monomial::new(e))
                })
                .collect();
            Polynomial::new(terms, n, order.clone())
        };
        let mut generators: Vec<_> = self.basis.iter().map(|p| extend(p, 0)).collect();
        let one = Polynomial::constant(F::one(), n, order.clone());
        generators.push(one.subtract(&extend(f, 1)));
        let basis = groebner_basis_f4(generators, false)?;
        Ok(basis.iter().any(Polynomial::is_constant))
    }

    /// The same ideal under `order`, via FGLM when zero-dimensional and F4 otherwise.
    #[allow(clippy::needless_pass_by_value)]
    pub fn change_order(&self, order: MonomialOrder) -> Result<Self, GroebnerError> {
        if order == self.order {
            return Ok(self.clone());
        }
        let basis = if self.is_zero_dimensional() {
            fglm::fglm(&self.basis, &order)?
        } else {
            groebner_basis_f4(
                self.basis
                    .iter()
                    .map(|p| p.reorder(order.clone()))
                    .collect(),
                true,
            )?
        };
        Self::from_groebner_basis(basis)
    }
}

impl<F: Field> Ideal<F> {
    /// Wrap a Groebner basis, reducing it to canonical form.
    pub fn from_groebner_basis(basis: Vec<Polynomial<F>>) -> Result<Self, GroebnerError> {
        let basis = finish_basis(prepare_input(basis)?, true)?;
        let (nvars, order) = (basis[0].nvars, basis[0].order.clone());
        Ok(Self {
            basis,
            nvars,
            order,
        })
    }

    pub fn basis(&self) -> &[Polynomial<F>] {
        &self.basis
    }

    pub fn order(&self) -> &MonomialOrder {
        &self.order
    }

    pub fn nvars(&self) -> usize {
        self.nvars
    }

    pub fn normal_form(&self, f: &Polynomial<F>) -> Result<Polynomial<F>, GroebnerError> {
        Ok(f.reorder(self.order.clone()).reduce(&self.basis)?)
    }

    pub fn contains(&self, f: &Polynomial<F>) -> Result<bool, GroebnerError> {
        Ok(self.normal_form(f)?.is_zero())
    }

    /// True when the ideal is the whole ring.
    pub fn is_trivial(&self) -> bool {
        self.basis.iter().any(Polynomial::is_constant)
    }

    pub fn is_zero_dimensional(&self) -> bool {
        fglm::is_zero_dimensional(&self.basis)
    }

    /// Monomials not divisible by any leading monomial, or `None` if infinitely many.
    pub fn standard_monomials(&self) -> Option<Vec<Monomial>> {
        let mut monomials = fglm::standard_monomials(&self.basis)?;
        monomials.sort_by(|a, b| a.compare(b, &self.order));
        Some(monomials)
    }

    /// Dimension of the quotient ring as a vector space, or `None` if infinite.
    pub fn vector_space_dimension(&self) -> Option<usize> {
        self.standard_monomials().map(|m| m.len())
    }

    /// Matrix of multiplication by variable `var` on the standard monomial basis, column major.
    pub fn multiplication_matrix(&self, var: usize) -> Result<Option<Vec<Vec<F>>>, GroebnerError> {
        let Some(monomials) = self.standard_monomials() else {
            return Ok(None);
        };
        let x = Monomial::variable(var, self.nvars);
        let mut matrix = Vec::with_capacity(monomials.len());
        for m in &monomials {
            let image =
                Polynomial::monomial(m.multiply(&x), self.order.clone()).reduce(&self.basis)?;
            let column = monomials
                .iter()
                .map(|b| {
                    image
                        .terms
                        .iter()
                        .find(|t| &t.monomial == b)
                        .map_or_else(F::zero, |t| t.coefficient.clone())
                })
                .collect();
            matrix.push(column);
        }
        Ok(Some(matrix))
    }
}
